name: CozyCup Backend - CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test-lint-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test

      - name: Docker build (npm script)
        run: npm run docker:build

      - name: Save image as tar
        run: docker save cozycup-api:dev -o cozycup-api-dev.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: cozycup-api-dev-image
          path: cozycup-api-dev.tar
          if-no-files-found: error
